#!/usr/bin/env bash
#
# start.sh — self-calibrating startup pipeline for the event-driven stack.
#
# The machine cannot be measured by Compose itself, so we measure it HERE
# (before instantiation), derive per-service resource ceilings from the host's
# RAM and CPU count, write them to .env (which docker compose interpolates into
# docker-compose.yml), bring the stack up, and launch the memory watchdog in the
# background so the host can never be driven into a freeze.
#
# Usage:
#   scripts/start.sh              # calibrate + up -d + start watchdog
#   NO_WATCHDOG=1 scripts/start.sh   # calibrate + up -d, no watchdog
#   DRY_RUN=1 scripts/start.sh    # print the calibrated .env and exit
#
# See docs/07_WATCHDOG.md for the formula and rationale.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

ENV_FILE="$REPO_ROOT/.env"
WATCHDOG="$REPO_ROOT/scripts/watchdog.sh"

# --- resolve the compose command (v2 plugin vs legacy binary) ----------------
if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  echo "ERROR: neither 'docker compose' nor 'docker-compose' is available." >&2
  exit 1
fi

# --- measure the host --------------------------------------------------------
# MemTotal is in kB in /proc/meminfo; convert to MB.
TOTAL_MB=$(awk '/^MemTotal:/ {printf "%d", $2/1024}' /proc/meminfo)
NPROC=$(nproc)

if [ -z "$TOTAL_MB" ] || [ "$TOTAL_MB" -le 0 ]; then
  echo "ERROR: could not read MemTotal from /proc/meminfo." >&2
  exit 1
fi

# --- calibrate ---------------------------------------------------------------
# Reserve headroom for the OS/IDE/browser: the larger of 2GB or 40% of total.
# The remainder is the stack budget, split by weight across the four services.
HEADROOM_MB=$(( TOTAL_MB * 40 / 100 ))
if [ "$HEADROOM_MB" -lt 2048 ]; then HEADROOM_MB=2048; fi

BUDGET_MB=$(( TOTAL_MB - HEADROOM_MB ))
if [ "$BUDGET_MB" -lt 1024 ]; then
  echo "WARNING: only ${BUDGET_MB}MB left for the stack after headroom on a" >&2
  echo "         ${TOTAL_MB}MB host. Falling back to a 1024MB minimum budget;" >&2
  echo "         expect tight limits. Close other apps or use a bigger machine." >&2
  BUDGET_MB=1024
fi

# Weights: kafka 45%, postgres 20%, app 20%, zookeeper 15%.
KAFKA_MB=$(( BUDGET_MB * 45 / 100 ))
POSTGRES_MB=$(( BUDGET_MB * 20 / 100 ))
APP_MB=$(( BUDGET_MB * 20 / 100 ))
ZK_MB=$(( BUDGET_MB * 15 / 100 ))

# JVM heap ~= 40% of the container's mem_limit for the JVM-based services.
KAFKA_HEAP_MB=$(( KAFKA_MB * 40 / 100 ))
ZK_HEAP_MB=$(( ZK_MB * 40 / 100 ))

# Node old-space ~= 75% of the app's mem_limit (leaves room for the rest of RSS).
APP_HEAP_MB=$(( APP_MB * 75 / 100 ))

# CPUs proportional to nproc (same weights), floored so nothing gets 0.
cpus_share() { awk -v n="$NPROC" -v w="$1" 'BEGIN{v=n*w; if(v<0.5)v=0.5; printf "%.1f", v}'; }
KAFKA_CPUS=$(cpus_share 0.40)
POSTGRES_CPUS=$(cpus_share 0.25)
APP_CPUS=$(cpus_share 0.25)
ZK_CPUS=$(cpus_share 0.15)

# --- write .env (consumed by docker compose interpolation) -------------------
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/start.sh — DO NOT EDIT BY HAND.
# Host measured: ${TOTAL_MB}MB RAM, ${NPROC} CPUs.
# Headroom reserved for OS: ${HEADROOM_MB}MB. Stack budget: ${BUDGET_MB}MB.
KAFKA_MEM_LIMIT=${KAFKA_MB}m
KAFKA_CPUS=${KAFKA_CPUS}
KAFKA_HEAP_OPTS=-Xmx${KAFKA_HEAP_MB}m -Xms$(( KAFKA_HEAP_MB / 2 ))m
POSTGRES_MEM_LIMIT=${POSTGRES_MB}m
POSTGRES_CPUS=${POSTGRES_CPUS}
APP_MEM_LIMIT=${APP_MB}m
APP_CPUS=${APP_CPUS}
APP_NODE_OPTIONS=--max-old-space-size=${APP_HEAP_MB}
ZK_MEM_LIMIT=${ZK_MB}m
ZK_CPUS=${ZK_CPUS}
ZK_HEAP_OPTS=-Xmx${ZK_HEAP_MB}m -Xms$(( ZK_HEAP_MB / 2 ))m
EOF

echo "Calibrated for ${TOTAL_MB}MB / ${NPROC} CPUs — stack budget ${BUDGET_MB}MB:"
echo "  kafka=${KAFKA_MB}m/${KAFKA_CPUS}cpu  postgres=${POSTGRES_MB}m/${POSTGRES_CPUS}cpu  app=${APP_MB}m/${APP_CPUS}cpu  zookeeper=${ZK_MB}m/${ZK_CPUS}cpu"

if [ "${DRY_RUN:-0}" = "1" ]; then
  echo "--- .env (dry run, stack not started) ---"
  cat "$ENV_FILE"
  exit 0
fi

# --- bring the stack up ------------------------------------------------------
echo "Starting stack: ${COMPOSE[*]} up -d"
"${COMPOSE[@]}" up -d

# --- launch the watchdog -----------------------------------------------------
if [ "${NO_WATCHDOG:-0}" = "1" ]; then
  echo "Watchdog NOT started (NO_WATCHDOG=1). Run '${WATCHDOG}' yourself to enable it."
  exit 0
fi

if [ ! -x "$WATCHDOG" ]; then
  echo "WARNING: $WATCHDOG is missing or not executable; skipping watchdog." >&2
  exit 0
fi

nohup "$WATCHDOG" >"$REPO_ROOT/scripts/watchdog.log" 2>&1 &
echo $! > "$REPO_ROOT/scripts/.watchdog.pid"
echo "Watchdog running in background (pid $(cat "$REPO_ROOT/scripts/.watchdog.pid")), logging to scripts/watchdog.log."
echo "Stop it with: kill \$(cat scripts/.watchdog.pid)"
